services:
  evocelot-prometheus:
    container_name: evocelot-prometheus
    volumes:
      - '../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    image: prom/prometheus:v2.50.0
    ports:
      - '9090:9090'
  evocelot-grafana:
    container_name: evocelot-grafana
    volumes:
      - '../config/grafana/provisioning/:/etc/grafana/provisioning/'
    image: grafana/grafana:10.2.4
    ports:
      - '3000:3000'
  evocelot-jaeger:
    container_name: evocelot-jaeger
    image: jaegertracing/all-in-one:1.54
    volumes:
      - '../config/jaeger/sampling_strategies.json:/etc/jaeger/sampling_strategies.json'
    ports:
      - '14250:14250'
      - '16686:16686'
  evocelot-opentelemetry-collector:
    container_name: evocelot-opentelemetry-collector
    image: otel/opentelemetry-collector:0.96.0
    command: [ --config=/etc/otel-collector-config.yaml ]
    volumes:
      - ../config/opentelemetry/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ../config/jaeger/sampling_strategies.json:/etc/otelcol/sampling_strategies.json
    ports:
      - 4318:4318
      - 1234:1234
networks:
  default:
    name: evocelot-network
