template:
  service:
    sample:
      base:
        uri: http://localhost:8081
      management:
        uri: http://localhost:9991

testsuite:
  rest:
    sampleService:
      sample:
        baseUriKey: template.service.sample.base.uri
        path: /rest/sample/{id}
      samplePost:
        baseUriKey: template.service.sample.base.uri
        path: /rest/sample
