extensions:
  health_check:
receivers:
  otlp:
    protocols:
      http:
processors:
  batch:
exporters:
  prometheus:
    endpoint: "0.0.0.0:1234"
service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
  extensions: [health_check]